#!/usr/bin/env python3
"""design/analytics/events.md → AnalyticsEvents.cs (имена и типизированные методы) + AnalyticsLog.cs (JSONL) (Python stdlib).

Использование:
  python3 gen_analytics.py design/analytics/events.md --out <Assets/…/Analytics> [--namespace Game.Analytics] [--no-backend]

Детерминированно: одинаковый events.md → одинаковые файлы. Файлы помечены <auto-generated>, правка — через events.md.
Формат событий — metrics-plan (плагин gd): таблица ## Events, колонки Event, Params (name:type), Trigger, Serves.
Выход 1, если в events.md нет событий или параметр не разобран.
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "slice-build" / "scripts"))
import gdd_ids  # noqa: E402

EMPTY = {"", "—", "-", "–"}
PARAM = re.compile(r"^([a-z][a-z0-9_]*)\s*:\s*(int|float|bool|string|enum\[([^\]]+)\])$")
CS_TYPE = {"int": "int", "float": "float", "bool": "bool", "string": "string"}
CS_KEYWORDS = {"abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const",
               "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit",
               "extern", "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int",
               "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out",
               "override", "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
               "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try",
               "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"}

BACKEND = r'''// <auto-generated> gd-build analytics-build: локальный JSONL-бэкенд для плейтестов. Замена бэкенда — ADR в design/tech/adr/. </auto-generated>
using System;
using System.Globalization;
using System.IO;
using System.Text;
using UnityEngine;

namespace __NS__
{
    /// Пишет события в Application.persistentDataPath/analytics/<session>.jsonl, одна строка — одно событие.
    /// В сеть ничего не отправляет. Без согласия (Consent = false, по умолчанию) события отбрасываются.
    public static class AnalyticsLog
    {
        public static bool Consent { get; set; }
        public static string SessionId { get; } = Guid.NewGuid().ToString("N");
        public static string FilePath => Path.Combine(Application.persistentDataPath, "analytics", SessionId + ".jsonl");

        /// Строка JSON каждого записанного события (для тестов и отладки).
        public static event Action<string> Written;

        private static StreamWriter writer;

        public static void Send(string eventName, params (string key, object value)[] parameters)
        {
            if (!Consent) return;
            var sb = new StringBuilder(160);
            sb.Append("{\"ts\":\"").Append(DateTime.UtcNow.ToString("o", CultureInfo.InvariantCulture))
              .Append("\",\"t\":").Append(Time.realtimeSinceStartup.ToString("0.###", CultureInfo.InvariantCulture))
              .Append(",\"session\":\"").Append(SessionId)
              .Append("\",\"event\":\"").Append(Escape(eventName)).Append("\",\"params\":{");
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0) sb.Append(',');
                sb.Append('"').Append(Escape(parameters[i].key)).Append("\":");
                AppendValue(sb, parameters[i].value);
            }
            sb.Append("}}");
            string line = sb.ToString();
            try
            {
                if (writer == null)
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(FilePath));
                    writer = new StreamWriter(FilePath, true, new UTF8Encoding(false)) { AutoFlush = true };
                    Application.quitting += Close;
                }
                writer.WriteLine(line);
            }
            catch (Exception e) when (e is IOException || e is UnauthorizedAccessException)
            {
                Debug.LogWarning("AnalyticsLog: " + e.Message);   // аналитика не ломает игру
            }
            Written?.Invoke(line);
        }

        public static void Close()
        {
            writer?.Dispose();
            writer = null;
            Application.quitting -= Close;
        }

        private static void AppendValue(StringBuilder sb, object v)
        {
            switch (v)
            {
                case null: sb.Append("null"); break;
                case bool b: sb.Append(b ? "true" : "false"); break;
                case int i: sb.Append(i.ToString(CultureInfo.InvariantCulture)); break;
                case long l: sb.Append(l.ToString(CultureInfo.InvariantCulture)); break;
                case float f: sb.Append(float.IsNaN(f) || float.IsInfinity(f) ? "null" : f.ToString("R", CultureInfo.InvariantCulture)); break;
                case double d: sb.Append(double.IsNaN(d) || double.IsInfinity(d) ? "null" : d.ToString("R", CultureInfo.InvariantCulture)); break;
                default: sb.Append('"').Append(Escape(Convert.ToString(v, CultureInfo.InvariantCulture))).Append('"'); break;
            }
        }

        private static string Escape(string s)
        {
            var sb = new StringBuilder(s.Length + 8);
            foreach (char c in s)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < ' ') sb.Append("\\u").Append(((int)c).ToString("x4"));
                        else sb.Append(c);
                        break;
                }
            }
            return sb.ToString();
        }
    }
}
'''


def pascal(name):
    return "".join(p[:1].upper() + p[1:] for p in name.split("_") if p)


def camel(name):
    p = pascal(name)
    s = p[:1].lower() + p[1:]
    return "@" + s if s in CS_KEYWORDS else s


def xml(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def parse_events(path):
    rows = gdd_ids.table_rows(gdd_ids.find_section(gdd_ids.sections(gdd_ids.read(path)), "events") or [])
    events, errors = [], []
    for r in rows:
        ev = r.get("event", "").strip("` ")
        if not ev or "<" in ev:
            continue
        params = []
        raw = r.get("params", "").strip()
        if raw not in EMPTY:
            for p in re.split(r",\s*(?![^\[]*\])", raw):
                m = PARAM.match(p.strip())
                if not m:
                    errors.append(f"{ev}: параметр «{p.strip()}» не разобран (нужен name:type)")
                    continue
                typ = "string" if m.group(2).startswith("enum") else CS_TYPE[m.group(2)]
                params.append((m.group(1), typ, m.group(3)))
        events.append((ev, params, r.get("trigger", "").strip(), r.get("serves", "").strip()))
    return events, errors


def render_events(events, ns, source):
    out = [f"// <auto-generated> gd-build analytics-build из {source}. Не править руками. </auto-generated>"]
    if events:
        ev, params, _, _ = events[0]
        args = ", ".join(f"{camel(n)}: {'0' if t == 'int' else '0f' if t == 'float' else 'false' if t == 'bool' else chr(34) * 2}"
                         for n, t, _ in params)
        out.append(f"// Использование: AnalyticsEvents.{pascal(ev)}({args});")
    out += [f"namespace {ns}", "{", "    public static class AnalyticsEvents", "    {",
            "        public static class Names", "        {"]
    out += [f'            public const string {pascal(ev)} = "{ev}";' for ev, _, _, _ in events]
    out += ["        }", ""]
    for ev, params, trigger, serves in events:
        note = " · ".join(x for x in (trigger, f"Serves: {serves}" if serves not in EMPTY else "") if x and x not in EMPTY)
        if note:
            out.append(f"        /// <summary>{xml(note)}</summary>")
        for n, t, enum in params:
            if enum:
                out.append(f'        /// <param name="{camel(n).lstrip("@")}">{xml(enum)}</param>')
        sig = ", ".join(f"{t} {camel(n)}" for n, t, _ in params)
        body = "".join(f', ("{n}", {camel(n)})' for n, _, _ in params)
        out.append(f"        public static void {pascal(ev)}({sig}) =>")
        out.append(f"            AnalyticsLog.Send(Names.{pascal(ev)}{body});")
        out.append("")
    if out[-1] == "":
        out.pop()
    out += ["    }", "}", ""]
    return "\n".join(out)


def main():
    gdd_ids.utf8_stdout()
    ap = argparse.ArgumentParser()
    ap.add_argument("events")
    ap.add_argument("--out", required=True)
    ap.add_argument("--namespace", default="Game.Analytics")
    ap.add_argument("--no-backend", action="store_true")
    a = ap.parse_args()

    events, errors = parse_events(a.events)
    for e in errors:
        print(f"FAIL {e}")
    if not events:
        print("FAIL: в events.md нет таблицы ## Events с событиями")
        return 1
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    src = "design/analytics/" + Path(a.events).name
    files = {"AnalyticsEvents.cs": render_events(events, a.namespace, src)}
    if not a.no_backend:
        files["AnalyticsLog.cs"] = BACKEND.replace("__NS__", a.namespace)
    for name, text in files.items():
        (out / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"Записан {out / name}")
    n_params = sum(len(p) for _, p, _, _ in events)
    print(f"Событий: {len(events)} · параметров: {n_params} · namespace {a.namespace} · бэкенд: {'нет' if a.no_backend else 'JSONL'}")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
