#!/usr/bin/env python3
"""Headless-настройка FMOD for Unity: то же, что Setup Wizard, без открытия редактора (Python stdlib).

Использование:
  python3 fmod_unity_setup.py <unity-project> --fspro <FMOD>/<project>.fspro [--unity <Unity.exe>] [--gitignore] [--dry-run]

Что делает (редактор должен быть закрыт, пакет FMOD for Unity — импортирован):
  1. Кладёт временный editor-скрипт в Assets/_GdFmodSetup/ (свой asmdef со ссылками на FMODUnity, FMODUnityEditor).
  2. Запуск Unity №1: StagingSystem.Startup() — переносит нативные библиотеки из Plugins/FMOD/staging
     (на свежей установке без этого кэш событий не строится).
  3. Запуск Unity №2 (новый процесс — чтобы подхватились библиотеки): путь к .fspro (относительный, если диск тот же),
     путь к банкам <проект>/Build, EventManager.RefreshBanks(); печатает число событий, банков, валидность кэша.
  4. Удаляет Assets/_GdFmodSetup (всегда, даже при ошибке). --gitignore — дописывает в .gitignore блок из
     Setup Wizard → Source Control (Cache, банки в StreamingAssets, fmod_editor.log), если его нет.
--dry-run — ничего не меняет, печатает путь к проекту Studio, редактор и команды.
Не делает: StudioListener в сцене, загрузку банков, вызовы в коде — это чеклист references/fmod-integration.md §4.
Выход: 0 — настроено (событий > 0, кэш валиден); 1 — Unity завершился с ошибкой, ошибки компиляции или кэш пуст;
2 — не Unity-проект, нет пакета FMOD for Unity, нет .fspro, редактор открыт или не найден.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "slice-build" / "scripts"))
import preflight  # noqa: E402

TMP_DIR = "_GdFmodSetup"
IGNORE_MARK = "# FMOD for Unity (Setup Wizard → Source Control)"
IGNORE_BLOCK = f"""
{IGNORE_MARK}
!/[Aa]ssets/Plugins/FMOD/**/lib/*
/[Aa]ssets/Plugins/FMOD/Cache/*
/[Aa]ssets/StreamingAssets/**/*.bank
/[Aa]ssets/StreamingAssets/**/*.bank.meta
fmod_editor.log
"""
ASMDEF = ('{ "name": "GdFmodSetup.Editor", "references": ["FMODUnity", "FMODUnityEditor"], '
          '"includePlatforms": ["Editor"], "autoReferenced": false }\n')
CS = """// <auto-generated> gd-build fmod-sync: fmod_unity_setup.py. Временный файл, удаляется после запуска. </auto-generated>
using FMODUnity;
using UnityEditor;
using UnityEngine;

public static class GdFmodSetup
{
    const string Project = "__PROJECT__";
    const string Banks = "__BANKS__";

    public static void Stage()
    {
        var step = StagingSystem.Startup();
        AssetDatabase.Refresh();
        Debug.Log("[gd-fmod] stage=" + (step == null ? "done" : step.Name) +
                  " staging=" + AssetDatabase.IsValidFolder("Assets/Plugins/FMOD/staging"));
    }

    public static void Configure()
    {
        var settings = Settings.Instance;
        var so = new SerializedObject(settings);
        so.FindProperty("HasSourceProject").boolValue = true;
        so.FindProperty("HasPlatforms").boolValue = true;
        so.FindProperty("sourceProjectPath").stringValue = Project;
        so.FindProperty("sourceBankPath").stringValue = Banks;
        so.ApplyModifiedPropertiesWithoutUndo();
        EditorUtility.SetDirty(settings);
        AssetDatabase.SaveAssets();
        EventManager.RefreshBanks();
        AssetDatabase.SaveAssets();
        Debug.Log("[gd-fmod] valid=" + EventManager.IsValid + " events=" + EventManager.Events.Count +
                  " banks=" + EventManager.Banks.Count + " project=" + settings.SourceProjectPath);
        foreach (var e in EventManager.Events) Debug.Log("[gd-fmod] event " + e.Path);
    }
}
"""


def studio_path(project, fspro):
    """Путь к .fspro так, как его пишет Setup Wizard: относительный от Unity-проекта, если диск тот же."""
    try:
        rel = os.path.relpath(Path(fspro).resolve(), Path(project).resolve())
    except ValueError:            # разные диски в Windows
        rel = str(Path(fspro).resolve())
    return rel.replace(os.sep, "/")


def bank_dir(project_path):
    return project_path.rsplit("/", 1)[0] + "/Build" if "/" in project_path else "Build"


def render_cs(project_path):
    return CS.replace("__PROJECT__", project_path).replace("__BANKS__", bank_dir(project_path))


def find_unity(project, explicit):
    if explicit:
        return Path(explicit) if Path(explicit).exists() else None
    m = re.search(r"m_EditorVersion:\s*(\S+)",
                  (Path(project) / "ProjectSettings/ProjectVersion.txt").read_text(encoding="utf-8", errors="replace"))
    return next((c for c in preflight.editor_candidates(m.group(1)) if c.exists()), None) if m else None


def run_unity(unity, project, method, log):
    exe = unity / "Contents/MacOS/Unity" if unity.suffix == ".app" else unity
    cmd = [str(exe), "-batchmode", "-nographics", "-quit", "-projectPath", str(project),
           "-executeMethod", method, "-logFile", str(log)]
    code = subprocess.run(cmd, capture_output=True).returncode
    text = Path(log).read_text(encoding="utf-8", errors="replace") if Path(log).is_file() else ""
    return code, text


def main():
    preflight.utf8_stdout()
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--fspro", required=True)
    ap.add_argument("--unity", default=None)
    ap.add_argument("--gitignore", action="store_true")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    proj, fspro = Path(a.project), Path(a.fspro)
    if not (proj / "ProjectSettings/ProjectVersion.txt").is_file():
        print(f"FAIL: {proj} — не Unity-проект (нет ProjectSettings/ProjectVersion.txt)")
        return 2
    if not (proj / "Assets/Plugins/FMOD/src").is_dir():
        print("FAIL: пакет FMOD for Unity не импортирован (нет Assets/Plugins/FMOD/src) — "
              "скачивание с fmod.com — шаг человека, импорт: Unity -batchmode -quit -importPackage <.unitypackage>")
        return 2
    if fspro.suffix != ".fspro" or not fspro.is_file():
        print(f"FAIL: {fspro} — нет файла проекта FMOD Studio (.fspro)")
        return 2
    if (proj / "Temp/UnityLockfile").exists():
        print("FAIL: редактор открыт (Temp/UnityLockfile) — закрой его или пройди FMOD → Setup Wizard вручную")
        return 2
    unity = find_unity(proj, a.unity)
    if unity is None:
        print("FAIL: редактор Unity версии проекта не найден — укажи --unity <путь к Unity.exe>")
        return 2

    rel = studio_path(proj, fspro)
    print(f"Unity-проект: {proj.resolve()} · редактор: {unity}")
    print(f"Проект Studio: {rel} · банки: {bank_dir(rel)}")
    if not (fspro.parent / "Build").is_dir():
        print("WARN: в проекте Studio нет Build/ — собери банки: fmodstudiocl -build -platforms Desktop <проект>.fspro")
    if a.dry_run:
        print("Dry run: запуски -executeMethod GdFmodSetup.Stage и GdFmodSetup.Configure не выполнялись")
        return 0

    tmp = proj / "Assets" / TMP_DIR
    logs = Path(tempfile.mkdtemp(prefix="gd-fmod-"))
    try:
        (tmp / "Editor").mkdir(parents=True, exist_ok=True)
        (tmp / "Editor/GdFmodSetup.Editor.asmdef").write_text(ASMDEF, encoding="utf-8", newline="\n")
        (tmp / "Editor/GdFmodSetup.cs").write_text(render_cs(rel), encoding="utf-8", newline="\n")
        results = {}
        for method in ("Stage", "Configure"):
            code, log = run_unity(unity, proj, f"GdFmodSetup.{method}", logs / f"{method}.log")
            errors = sorted(set(re.findall(r"^.*error CS\d+.*$", log, re.M)))
            results[method] = (code, [l.split("[gd-fmod] ", 1)[1] for l in log.splitlines() if "[gd-fmod] " in l])
            for e in errors[:10]:
                print(f"FAIL {e.strip()}")
            if code != 0 or errors:
                print(f"FAIL: Unity ({method}) завершился с кодом {code} — лог {logs / (method + '.log')}")
                return 1
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
        Path(str(tmp) + ".meta").unlink(missing_ok=True)

    lines = results["Stage"][1] + results["Configure"][1]
    for l in lines:
        print(f"  {l}")
    summary = next((l for l in lines if l.startswith("valid=")), "")
    m = re.search(r"valid=(\w+) events=(\d+) banks=(\d+)", summary)
    if a.gitignore:
        gi = proj / ".gitignore"
        text = gi.read_text(encoding="utf-8") if gi.is_file() else ""
        if IGNORE_MARK not in text and "fmod_editor.log" not in text:
            with gi.open("a", encoding="utf-8", newline="\n") as f:
                f.write(IGNORE_BLOCK)
            print("Дописан .gitignore: блок FMOD for Unity")
    if not m or m.group(1) != "True" or m.group(2) == "0":
        print("FAIL: кэш событий пуст или невалиден — банки собраны? (fmodstudiocl -build), путь к проекту верный?")
        return 1
    print(f"Итог: PASS · событий (со снапшотами): {m.group(2)} · банков: {m.group(3)} · логи: {logs}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
